tplink-safeloader: add support for TP-Link RE205 V3
openwrt/firmware-utils pull request #22
Opened 2024-02-09 18:35 UTC by slo617

I have modified tplink-safeloader utility and added support to create factory images for TP-Link RE205 V3 devices.
I have tested the resulting factory image on my own hardware, I could successfully upgrade my device with an OpenWRT image.

Information like "special_id"s that was needed to modify the tool has been read out from an original firmware upgrade package.

2024-02-10 15:40 UTC, svanheule requested changes
Thanks for the patch!

Could you add some of the pull request description (where you got the info, how you tested it) to the commit message? One small nit, but looks good otherwise.

2024-02-10 15:40 UTC, svanheule commented on src/tplink-safeloader.c
> +  /** Firmware layout for the RE205 v3 */
Please align this comment with the opening curly brace.

2024-02-10 18:28 UTC, slo617 commented
Thanks for the review!

I modified the commit as requested.

2024-02-11 07:49 UTC, svanheule approved these changes
Thanks for the update! Looks good to me, I'll merge this.

2024-02-11 07:51 UTC, closed without merging